### ISSUE TITLE
Deployment Target

### ISSUE THREAD

**Issue by OliverZiegler** [likedan/KDIntroView#3]
Why did you change deployment target to iOS 9?
Is there any good reason?

**Comment by likedan** [comment]
I was trying to figured out how Cocoapod work with Swift 3. The cocoapod compiler complain about Swift 3 syntax.

**Comment by OliverZiegler** [comment]
Bumping up the deployment target is not the right way ;)
As swift 3 can be used with iOS8 and your pod does not use any API that is only available for >iOS8 you should stay at iOS8.

Currently cocoapods defaults to swift 2.3 I think.
So you could make a post-install hook to set this to 3.0.

Perhaps this could fix your issue for further versions:
https://github.com/CocoaPods/CocoaPods/pull/5841
But you will need cocoapods version 1.1.0-beta for this to work I think.

**Comment by likedan** [comment]
Thanks for letting me know. I’ll address that when I’m available. Super busy recently! But thanks again!
